# Base nuclear explosions configuration
nuclear-explosion-settings:
  shockwave-config:
    base-radius: 800 # The radius (in blocks) of the shockwave
    base-height: 300 # The height (in blocks) of the shockwave, all structures under this height will be destroyed,
    # and the range is like this [explosion height, explosion height + height]
  crater-config:
    base-radius: 180 # The radius (in blocks) of the crater

  fallout-config:
    base-radius: 1600 # The base fallout spread radius in blocks (XZ plane)
    base-spread-height: 150 # The base fallout height in blocks (Y axis), starting from the explosion center
    base-underground-spread-depth: 30 # Depth value in blocks of the fallout underground spread

  flash-config:
    base-radius: 1000 # The distance in blocks from the explosion center where the flash will be visible

  thermal-config:
    base-radius: 1000 # The distance in blocks from the explosion center the thermal damage will be applied

  sound-config:
    sound-speed: 50 # The speed of the sound in blocks per second, this is used to calculate the sound delay



# Plugin pack generator settings
# This includes settings for the resource pack and data pack
pack-generator:
  resource-pack:
    automatic-generation: true # Default: true; Disable this only if you want to use a custom resource pack on your server
    resource-server-port: 8000 # Default: 8000; The port that the server will use to serve the resource pack
  pack-format-fallback:
    # These are the pack format fallbacks, to use if the plugin release is before a certain minecraft version
    # You can read more about pack format here: https://minecraft.fandom.com/wiki/Pack_format
    resource-pack: 46
    data-pack: 71