# Pack format fallbacks, to use if the plugin release is before a certain minecraft version, used for resource pack and data pack generation
# You can read more about pack format here: https://minecraft.fandom.com/wiki/Pack_format
pack_format_fallback:
  resource_pack: 46
  data_pack: 71

# Resource pack server port, this is the port that the server will use to serve the resource pack
resource_pack_server_port: 8000